{
    "th07 Menu Start": "게임을 시작합니다.",
    "th07 Menu Extra Start": "엑스트라 스테이지를 시작합니다.",
    "th07 Menu Practice Start": "스테이지를 선택해 연습을 시작합니다.",
    "th07 Menu Result": "과거의 스코어와 스펠카드 획득 이력을 볼 수 있습니다.",
    "th07 Menu Music Room": "음악을 들을 수 있습니다.",
    "th07 Menu Replay": "리플레이를 볼 수 있습니다.",
    "th07 Menu Option": "각종 설정을 할 수 있습니다.",
    "th07 Menu Quit": "게임을 종료합니다.",
    "th07 Option Player": "초기 잔기 수를 변경합니다. (초기설정 3)",
    "th07 Option Graphic": "화면의 색상 수를 변경합니다. 32BIT에서 가장 좋게 표시됩니다.",
    "th07 Option BGM": "BGM의 재생방법을 변경합니다. (초기설정 WAV)",
    "th07 Option Sound": "효과음 재생 여부를 선택합니다.",
    "th07 Option Window Mode": "창 모드와 전체화면 모드를 선택합니다.",
    "th07 Option Slow Mode": "탄이 많을 경우 고의로 처리지연 시킵니다. (점수, 리플레이 기록 불가)",
    "th07 Option Reset": "모두 초기설정으로 되돌립니다.",
    "th07 Option Key Config": "패드 조작의 버튼 배치를 변경합니다.",
    "th07 Option Quit": "설정을 종료합니다.",
    "th07 Key Shot": "샷, 결정 버튼을 설정합니다.",
    "th07 Key Bomb": "봄, 캔슬 버튼을 설정합니다.",
    "th07 Key Slow": "저속이동 버튼을 설정합니다.",
    "th07 Key Skip": "메세지 스킵 버튼을 설정합니다.",
    "th07 Key Pause": "일시정지 버튼을 설정합니다.",
    "th07 Key Up": "↑버튼을 설정합니다.",
    "th07 Key Down": "↓버튼을 설정합니다.",
    "th07 Key Left": "←버튼을 설정합니다.",
    "th07 Key Right": "→버튼을 설정합니다.",
    "th07 Key ShotSlow": "버튼을 누르고 있을 시 저속이동이 되도록 합니다.",
    "th07 Key Reset": "초기설정으로 되돌립니다.",
    "th07 Key Quit": "키 설정을 종료합니다.",
    "th08 Menu Spell Practice": "적과 스펠카드전을 시작합니다.",
    "th08 Option BGM Volume": "BGM 음량을 조정합니다.",
    "th08 Option SE Volume": "효과음의 음량을 조정합니다.",
    "th09 Menu Story Start": "화영총 모드를 시작합니다.",
    "th09 Menu Extra Start": "엑스트라 모드를 시작합니다.",
    "th09 Menu Replay": "리플레이를 재생합니다.",
    "th09 Menu Result": "기록을 봅니다.",
    "th09 Key Side": "1P, 2P 를 선택합니다",
    "th06 Bomb Reimu A": "영부 \"몽상봉인\"",
    "th06 Bomb Reimu B": "몽부 \"봉마진\"",
    "th06 Bomb Marisa A": "마부 \"스타더스트 레버리\"",
    "th06 Bomb Marisa B": "연부 \"마스터 스파크\"",
    "th07 Bomb Reimu A unfocused": "영부 \"몽상봉인 산\"",
    "th07 Bomb Reimu A focused": "영부 \"몽상봉인 집\"",
    "th07 Bomb Reimu B focused": "몽부 \"이중결계\"",
    "th07 Bomb Marisa A focused": "마부 \"밀키 웨이\"",
    "th07 Bomb Marisa B unfocused": "연부 \"논디렉셔널 레이저\"",
    "th07 Bomb Sakuya A unfocused": "환부 \"인디스크리미네이트\"",
    "th07 Bomb Sakuya A focused": "환부 \"살인 인형\"",
    "th07 Bomb Sakuya B unfocused": "시부 \"퍼펙트 스퀘어\"",
    "th07 Bomb Sakuya B focused": "시부 \"프라이빗 스퀘어\"",
    "th08 Bomb Reimu": "영부 \"몽상묘주\"",
    "th08 Bomb Reimu Last": "신령 \"몽상봉인 순\"",
    "th08 Bomb Yukari": "경부 \"사중결계\"",
    "th08 Bomb Yukari Last": "경계 \"영야사중결계\"",
    "th08 Bomb Marisa Last": "마포 \"파이널 스파크\"",
    "th08 Bomb Alice": "마부 \"아트풀 새크리파이스\"",
    "th08 Bomb Alice Last": "마조 \"리턴 인애니메이트니스\"",
    "th08 Bomb Sakuya Last": "환장 \"밤안개의 환영 살인귀\"",
    "th08 Bomb Remilia": "홍부 \"불야성 레드\"",
    "th08 Bomb Remilia Last": "홍마 \"스칼렛 데빌\"",
    "th08 Bomb Youmu": "인부 \"현세참\"",
    "th08 Bomb Youmu Last": "인귀 \"미래영겁참\"",
    "th08 Bomb Yuyuko": "사부 \"개스틀리 드림\"",
    "th08 Bomb Yuyuko Last": "사접 \"화서의 영면\"",
    "th08 Spell Dissolve": "\"디졸브 스펠\"",
    "th08 Spell Resurrection": "\"리저렉션\"",
    "th08 Music Room spoiler 1": "***주의***",
    "th08 Music Room spoiler 2": "이 곡은 아직 게임에서 연주되지 않았습니다.",
    "th08 Music Room spoiler 3": "직접 플레이하기 전에 듣고 싶지 않거나 코멘트를 보고 싶지 않으면",
    "th08 Music Room spoiler 4": "최대한 빨리 여기서 벗어나는 것을 추천합니다.",
    "th08 Music Room spoiler 5": " ",
    "th08 Music Room spoiler 6": "(하지만, 여기서 결정 버튼을 누르면 다른 곡과 마찬가지로",
    "th08 Music Room spoiler 7": "곡이 재생되고 코멘트가 표시되므로 주의)",
    "th09 Music Room spoiler 1": "***** 주의 *****",
    "th09 Music Room spoiler 2": "이 곡은 아직 게임에서 재생된 적이 없습니다.",
    "th09 Music Room spoiler 3": "일단 들을 수는 있지만, 곡명과 코멘트는 볼 수 없습니다.",
    "th10 Music Room spoiler 1": "<c$**선택한 곡은 아직 게임에서 재생된 적이 없습니다**$>",
    "th10 Music Room spoiler 2": "<c$코멘트 스포일러를 주의해 주세요.$>",
    "th10 Music Room spoiler 3": "<c$그래도 재생하시겠습니까?$>",
    "th10 Music Room spoiler 4": "<c$재생하려면 한 번 더 선택 버튼을 눌러 주십시오.$>",
    "th10 Music Room spoiler 5": "<c$재생하지 않으려면 커서를 이동해 주십시오.$>",
    "th13 spell nothing": "Nothing…",
    "th143 Trophy Format": "『%s』",
    "th143 Trophy Get": "이명을 얻었다",
    "th10 Dialog Prompt": "윈도우 모드를 선택해 주세요",
    "th10 Dialog Fullscreen": "전체 화면",
    "th10 Dialog Always ask": "실행할 때마다 묻기",
    "th11 Dialog Fullscreen 640": "풀 스크린(640×480)",
    "th11 Dialog Window 640": "윈도우(640×480)",
    "th11 Dialog Window 960": "윈도우(960×720)",
    "th11 Dialog Window 1280": "윈도우(1280×960)",
    "th11 Dialog Game Start": "게임 실행",
    "th14 Dialog Prompt": "해상도를 선택해 주세요",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720",
    "th14 Dialog 1280": "1280×960 (권장)",
    "th14 Dialog Fullscreen": "풀 스크린으로 실행하기",
    "th14 Dialog Always ask": "실행할 때마다 묻기",
    "th10 JP": "동방풍신록",
    "alcostg JP": "황혼주점",
    "th11 JP": "동방지령전",
    "th12 JP": "동방성련선",
    "th125 JP": "더블 스포일러",
    "th128 JP": "요정대전쟁",
    "th13 JP": "동방신령묘",
    "th14 JP": "동방휘침성",
    "th143 JP": "탄막 아마노자쿠",
    "th06 config": "동방홍마향 환경설정",
    "th07 config": "동방요요몽 환경설정",
    "th08 config": "동방영야초 환경설정",
    "th09 config": "동방화영총 환경설정",
    "th095 config": "동방문화첩 환경설정",
    "th10 config": "동방풍신록 환경설정",
    "alcostg config": "황혼주점 환경설정",
    "th11 config": "동방지령전 환경설정",
    "th12 config": "동방성련선 환경설정",
    "th125 config": "더블 스포일러 환경설정",
    "th128 config": "요정대전쟁 환경설정",
    "th13 config": "동방신령묘 환경설정",
    "th14 config": "동방휘침성 환경설정",
    "th143 config": "탄막 아마노자쿠 환경설정",
    "th06 up": "상 ",
    "th06 down": "하 ",
    "th06 left": "좌 ",
    "th06 right": "우 ",
    "th06 vertex": "버텍스 버퍼를 사용하지 않습니다",
    "th06 fog": "안개를 사용하지 않습니다",
    "th06 16bit textures": "16비트 텍스처 사용을 강제합니다",
    "th06 Gouraud shading": "고러드 셰이딩 사용을 억제합니다",
    "th06 color composition": "텍스처에 색상 합성을 하지 않습니다",
    "th06 rasterizer mode": "참조 래스터라이저 모드로 실행합니다",
    "th06 clear buffer": "매번 백 버퍼를 지웁니다",
    "th06 minimum graphics": "최소한의 그래픽만 표시합니다",
    "th06 depth test": "깊이 테스트를 OFF로 설정합니다",
    "th06 force frame": "강제로 60프레임을 유지합니다",
    "th06 fullscreen": "전체 화면",
    "th06 windowed": "창 모드",
    "th06 full rate": "매번 (기본)",
    "th06 half rate": "1/2회",
    "th06 third rate": "1/3회",
    "th06 32bits mode": "32비트",
    "th06 16bits mode": "16비트",
    "th06 accept": "확인",
    "th06 cancel": "취소",
    "th06 screen mode": "화면 모드",
    "th06 refresh rate": "출력 간격",
    "th06 colors": "색상 모드",
    "th06 pad X axis": "패드의 좌우 감도 (1～1000)",
    "th06 pad Y axis": "패드의 상하 감도 (1～1000)",
    "th06 check pad": "패드 십자 키 확인",
    "th06 config saved caption": "확인",
    "th06 config saved text": "환경설정을 새로 저장했습니다",
    "th07 16bits textures": "16Bits 텍스처 사용을 강제합니다",
    "th07 BGM memory": "배경음악을 메모리에 저장합니다",
    "th07 draw screen": "화면 주위를 매번 그립니다",
    "th07 VSync": "수직 동기화를 사용하지 않습니다",
    "th07 fullscreen": "전체 화면 (권장)",
    "th07 low effects": "최저",
    "th07 medium effects": "중간",
    "th07 high effects": "최고 (권장)",
    "th07 32bits mode": "32비트 (권장)",
    "th07 effect quality": "효과 품질",
    "th08 fog": "안개를 사용하지 않습니다 (비추천)",
    "th08 color composition": "텍스처에 색상 합성을 하지 않습니다 (금지)",
    "th08 depth test": "깊이 테스트를 OFF로 설정합니다 (비추천)",
    "th08 rasterizer mode": "참조 래스터라이저 모드로 실행합니다 (금지)",
    "th08 VSync": "수직 동기화를 하지 않습니다 (비추천)",
    "th09 full rate": "매번 (권장)",
    "th09 1P controller": "1P의 조작 방법",
    "th09 2P controller": "2P의 조작 방법",
    "th09 gamepad 1": "게임 패드 １",
    "th09 gamepad 2": "게임 패드 ２",
    "th09 all keyboard": "키보드 전체",
    "th09 left side keyboard": "왼쪽",
    "th09 right side keyboard": "오른쪽",
    "th09 no save": "저장하지 않고 종료",
    "th09 save": "저장하고 종료",
    "th10 faith meter": "신앙 감소 카운터를 플레이어 근처에 표시합니다",
    "th10 screen mode": "화면 모드",
    "th10 always ask": "매번 묻기",
    "th10 slowshot": "샷 버튼을 누르고 있으면 저속이동을 합니다",
    "th11 input latency": "입력 지연 시간",
    "th11 stable input": "안정 (보통 선택 시 제대로 움직이지 않는 경우)",
    "th11 normal input": "보통 (CPU 점유율 낮음)",
    "th11 automatic input": "자동 (최적의 반응 속도를 자동으로 뽑아냄) *권장",
    "th11 fast input": "고속 (자동 선택 시 정상 작동하지 않는 경우)",
    "th11 input description": "입력 지연 시간 옵션으로 입력 반응을 조금씩 조정할 수 있습니다.\n'안정' '보통'은 이전 작품까지의 반응 속도입니다.\n'자동'은 컴퓨터의 성능이 충분하면 빠른 반응을 기대할 수 있습니다.\n'고속'은 '자동'과 같은 지연 속도이지만, 일부 화면이 깨지는 경우가 있습니다.\n*다시 그리기 간격이 '매회'일 때는 무시됩니다*",
    "th11 always ask": "실행할 때마다 묻기",
    "th11 sensitivity description": "방향키 입력이 둔한 경우에는 줄이고, 너무 민감하면 늘려 주세요\n(기본값: 600)",
    "th11 joypad sensitivity": "게임 패드 감도",
    "th11 default": "설정 초기화",
    "Serif font": "NanumMyeongjo",
    "th15 JP": "동방김치전",
    "th15 config": "동방김치전 환경설정",
    "th08 Spell Practice Description": "스테이지　획득/도전가능/총 수 (괄호 안은 전 캐릭터 합계)",
    "th08 Spell Practice Percentages": "획득률　(캐릭터별/총합)",
    "DirectInput fix": "DirectInput을 사용",
    "DirectInput fix, layout-dependent shot key": "DirectInput을 사용 (샷 키: %c)",
    "th09 Menu Match Start": "대인전, 대CPU전, 관람모드를 시작합니다.",
    "th09 Menu Music Room": "뮤직룸에 들어갑니다.",
    "th09 Option BGM": "BGM의 재생 방식을 바꿉니다.(현재 MIDI는 지원되지 않습니다.)",
    "th09 Option Key Config": "조작키를 설정합니다.",
    "th09 Key Control Type": "PAD1,2:패드 사용, Full,Left,Right:키보드 사용",
    "th09 Key Charge Type": "차지 버튼의 작동 방식을 설정합니다.",
    "th09 Key Shot": "샷 버튼을 설정합니다.",
    "th09 Key Bomb": "봄 버튼을 설정합니다.",
    "th09 Key Slow": "저속이동버튼과 차지버튼을 설정합니다.",
    "th16": "동방천공장 ~ Hidden Star in Four Seasons.",
    "th01": "동방영이전 ~ The Highly Responsive to Prayers",
    "th02": "동방봉마록 ~ the Story of Eastern Wonderland",
    "th03": "동방몽시공 ~ Phantasmagoria of Dim.Dream",
    "th04": "동방환상향 ~ Lotus Land Story",
    "th05": "동방괴기담 ~ Mystic Square",
    "th06": "동방홍마향 ~ the Embodiment of Scarlet Devil.",
    "th07": "동방요요몽 ~ Perfect Cherry Blossom.",
    "th08": "동방영야초 ~ Imperishable Night.",
    "th09": "동방화영총 ~ Phantasmagoria of Flower View.",
    "th095": "동방문화첩 ~ Shoot the Bullet.",
    "th10": "동방풍신록 ~ Mountain of Faith.",
    "th11": "동방지령전 ~ Subterranean Animism.",
    "th12": "동방성련선 ~ Undefined Fantastic Object.",
    "th125": "더블 스포일러 ~ 동방문화첩",
    "th128": "요정대전쟁 ~ 동방삼월정",
    "th13": "동방신령묘 ~ Ten Desires.",
    "th14": "동방휘침성 ~ Double Dealing Character.",
    "th143": "탄막 아마노자쿠 ~ Impossible Spell Card.",
    "th15": "동방김치전 ~ Legacy of Josen Kingdom.",
    "th165": "비봉 나이트메어 다이어리 ~ Violet Detector.",
    "th07 Stats Header Easy": "Easy",
    "th07 Stats Header Normal": "Norm",
    "th07 Stats Header Hard": "Hard",
    "th07 Stats Header Lunatic": "Luna",
    "th07 Stats Header Extra": "Extra",
    "th07 Stats Header Phantasm": "Phants",
    "th07 Stats Header Total": "Total",
    "th07 Spell Result Character Select": "%s  %3d장 중 %3d장 획득 (캐릭터 전환↓↑)",
    "th07 Stats ReimuA": "하쿠레이 레이무 (영부)",
    "th07 Stats ReimuB": "하쿠레이 레이무 (몽부)",
    "th07 Stats MarisaA": "키리사메 마리사 (마부)",
    "th07 Stats MarisaB": "키리사메 마리사 (연부)",
    "th07 Stats SakuyaA": "이자요이 사쿠야 (환부)",
    "th07 Stats SakuyaB": "이자요이 사쿠야 (시부)",
    "th07 Stats Total (All Characters)": "전 주인공 합계            ",
    "Stats Time Since Startup": "가동시간",
    "Stats Total Playtime": "총 플레이 시간",
    "Stats Play Count": "플레이 횟수",
    "Stats Clear Count": "클리어 횟수",
    "Stats Continue": "컨티뉴 횟수",
    "Stats Practice": "연습 횟수",
    "Stats Retries": "재시도 횟수",
    "th08 Spell Result Character Select": "%3d/%3d (캐릭터 전환↓↑)",
    "th08 Stats Reimu & Yukari": "레이무&유카리        ",
    "th08 Stats Marisa & Alice": "마리사&앨리스        ",
    "th08 Stats Sakuya & Remilia": "사쿠야&레밀리아     ",
    "th08 Stats Youmu & Yuyuko": "요우무&유유코        ",
    "th08 Stats Reimu": "하쿠레이 레이무      ",
    "th08 Stats Yukari": "야쿠모 유카리         ",
    "th08 Stats Marisa": "키리사메 마리사      ",
    "th08 Stats Alice": "앨리스 마가트로이드",
    "th08 Stats Sakuya": "이자요이 사쿠야      ",
    "th08 Stats Remilia": "레밀리아 스칼렛      ",
    "th08 Stats Youmu": "콘파쿠 요우무         ",
    "th08 Stats Yuyuko": "사이교우지 유유코   ",
    "th08 Spell Practice Easy Mode": "첫달 (이지)",
    "th08 Spell Practice Normal Mode": "초승달 (노멀)",
    "th08 Spell Practice Hard Mode": "상현달 (하드)",
    "th08 Spell Practice Lunatic Mode": "온달 (루나틱)",
    "th08 Spell Practice Extra Mode": "보름달 (엑스트라)",
    "th08 Spell Practice Last Word": "극의 (라스트 워드)",
    "th08 Spell Practice List Description": "취득수/도전수 (괄호 안은 본편의 합계)",
    "th08 Spell Practice Owner/Difficulty Line": "사용자  %s        %s %s",
    "th08 Spell Practice Highscore Title": "취득수/도전수[최고점]    %s    전주인공 합계",
    "th08 Spell Practice Comment": "카드 보충설명",
    "th08 Spell Practice Last Spell": "Last",
    "th08 Spell Condition Line 1 205": "도전가능조건: 보름달(엑스트라)의 스펠카드를 7장 이상 얻고",
    "th08 Spell Condition Line 2 205": "　　　　　　　클리어한다.",
    "th08 Spell Condition Line 1 206": "도전가능조건: Final B를 두 캐릭터 이상 클리어한다.",
    "th08 Spell Condition Line 2 206 207 209": "　　　　　　　난이도 불문.",
    "th08 Spell Condition Line 1 207": "도전가능조건: Final B를 세 캐릭터 이상 클리어한다.",
    "th08 Spell Condition Line 1 208": "도전가능조건: 스펠카드 모드에서 스펠카드를 50장 이상 획득한다.",
    "th08 Spell Condition Line 2 208 211 217 220": "　　　　　　　전 캐릭터 합계.",
    "th08 Spell Condition Line 1 209": "도전가능조건: Final B를 네 캐릭터 이상 클리어한다.",
    "th08 Spell Condition Line 1 210": "도전가능조건: No.%.3d을(를) 획득한다.",
    "th08 Spell Condition Line 1 211": "도전가능조건: 스펠카드 모드에서 라스트 스펠을 15장 이상 획득한다.",
    "th08 Spell Condition Line 1 212": "도전가능조건: No.%.3d,%.3d을(를) 얻고,",
    "th08 Spell Condition Line 2 212": "　　　　　　　No.%.3d을(를) 한 번 본다.",
    "th08 Spell Condition Line 1 213": "도전가능조건: No.%.3d,%.3d,%.3d,%.3d을(를) 한 번씩 본다.",
    "th08 Spell Condition Line 2 213 214 222": "　　　　　　　획득할 필요는 없음.",
    "th08 Spell Condition Line 1 214": "도전가능조건: No.%.3d,%.3d,%.3d,%.3d을(를) 한 번씩 본다.",
    "th08 Spell Condition Line 1 215": "도전가능조건: 마리사 단독으로 초승달(노멀)의 스펠카드를",
    "th08 Spell Condition Line 2 215": "　　　　　　　전부 획득한다.",
    "th08 Spell Condition Line 1 216": "도전가능조건: 레이무 단독, 상현달(하드) 이상으로 Final B를",
    "th08 Spell Condition Line 2 216": "　　　　　　　노컨티뉴 클리어한다.",
    "th08 Spell Condition Line 1 217": "도전가능조건: 스펠카드 모드에서 스펠카드를 120장 이상 획득한다.",
    "th08 Spell Condition Line 1 218": "도전가능조건: Final B를 여섯 캐릭터 이상 클리어한다.",
    "th08 Spell Condition Line 2 218": " ",
    "th08 Spell Condition Line 1 219": "도전가능조건: 보름달(엑스트라)을 세 캐릭터 이상 클리어한다.",
    "th08 Spell Condition Line 1 220": "도전가능조건: 스펠카드 모드에서 라스트 스펠을 30장 이상 획득한다.",
    "th08 Spell Condition Line 1 221": "도전가능조건: 온달(루나틱)을 클리어한다.",
    "th08 Spell Condition Line 2 221": "　　　　　　　컨티뉴 가능, 캐릭터는 상관 없음.",
    "th08 Spell Condition Line 1 222": "도전가능조건: 이것 이외의 라스트워드를 한 번씩 본다.",
    "th105_init_failed": "초기화 실패",
    "th105_replay_return_to_select": "선택창으로 돌아갑니다. 리플레이를 저장합니까?",
    "th105_replay_return_to_title": "타이틀로 돌아갑니다. 리플레이를 저장합니까?",
    "th105_replay_saved": "리플레이를 저장했습니다.",
    "th105_replay_save": "리플레이를 저장합니까?",
    "th105_replay_delete": "삭제합니까?",
    "th105_continue": "계속하겠습니까? 앞으로 %d회",
    "th105_netplay_select_addr": "접속할 상대를 선택하세요",
    "th105_netplay_port": "사용할 포트 번호를 입력하세요",
    "th105_netplay_enter_addr": "접속할 IP 주소를 입력하세요",
    "th105_netplay_allow_spectating": "관전할 수 있도록 합니까?",
    "th105_netplay_await": "접속 수립중",
    "th105_netplay_no_spectating": "관전할 수 없습니다",
    "th105_netplay_game_not_available": "대전을 진행할 수 없습니다",
    "th105_netplay_connection_failed": "접속에 실패했습니다",
    "th105_netplay_connecting": "접속중",
    "th105_netplay_connect_for_match": "대전하겠습니까?",
    "th105_netplay_confirm_address": "로 접속합니다",
    "th105_netplay_already_playing": "이미 대전 중입니다",
    "th105_netplay_already_playing_spectate": "이미 대전 중입니다. 관전하겠습니까?",
    "th105_delete_failed": "삭제하지 못했습니다",
    "th105_delete_suceeded": "삭제했습니다",
    "th105_profile_save_changes": "생성을 마칩니다. 편집한 내용을 저장합니까?",
    "th105_profile_deck_too_big": "덱 카드수는 20장으로 맞추세요",
    "th105_profile_creation_failed": "을(를) 작성하지 못했습니다",
    "th105_profile_created": "을(를) 작성했습니다",
    "th105_profile_copied": "복사했습니다",
    "th105_profile_copy_failed": "복사하지 못했습니다",
    "th105_profil_rename_failed": "이름을 변경하지 못했습니다",
    "th105_profil_renamed": "이름을 변경했습니다",
    "th105_profile_overwrite": "에 덮어씁니까?",
    "th105_profile_will_copy": "을(를) 복사합니까?",
    "th105_profile_will_delete": "을(를) 삭제합니까?",
    "th123_replay_create_folder_failed": "리플레이 폴더를 생성하지 못 했습니다",
    "th123_profile_create_folder_failed": "프로필 폴더를 생성하지 못 했습니다",
    "th165 JP": "비봉 나이트메어 다이어리",
    "th16 config": "동방천공장 환경설정",
    "th165 config": "비봉 나이트메어 다이어리 환경설정",
    "th08 Stats Total Playtime": "총 플레이 시간  %.2d:%.2d:%.2d",
    "th08 Stats Time Since Startup": "기동 시간         %.2d:%.2d:%.2d",
    "th08 Stats Play Count": "플레이 횟수                Easy Norm Hard Luna Extra Total",
    "th08 Stats Clear Count": "클리어 횟수             %6d %6d %6d %6d %6d %6d",
    "th08 Stats Continue": "컨티뉴 횟수             %6d %6d %6d %6d %6d %6d",
    "th08 Stats Practice": "연습 횟수                %6d %6d %6d %6d %6d %6d",
    "th07 Stats Play Count": "플레이 횟수                   Easy Norm Hard Luna Extra Total",
    "th07 Stats Clear Count": "클리어 횟수                 %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue": "컨티뉴 횟수                 %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice": "연습 횟수                    %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries": "재시도 횟수                 %6d %6d %6d %6d %6d %6d",
    "th07 Stats Time Since Startup": "기동 시간         %.2d:%.2d:%.2d",
    "th07 Stats Total Playtime": "총 플레이 시간  %.2d:%.2d:%.2d",
    "th08 Stats Total (All Characters)": "전 주인공 합계        ",
    "th07 Stats Play Count +Phantasm": "플레이 횟수                   Easy Norm Hard Luna Extra Phants Total",
    "th07 Stats Clear Count +Phantasm": "클리어 횟수                 %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue +Phantasm": "컨티뉴 횟수                 %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries +Phantasm": "재시도 횟수                 %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice +Phantasm": "연습 횟수                    %6d %6d %6d %6d %6d %6d %6d",
    "th075": "동방췌몽상 ~ Immaterial and Missing Power.",
    "th105": "동방비상천 ~ Scarlet Weather Rhapsody.",
    "th123": "동방비상천칙 ~ 초대형 기뇰의 수수께끼를 쫓아서",
    "th13_ascii_spell_score": "SCORE %8d0  %4d/%4d",
    "th13_ascii_spell_unknown": "SCORE        00  ----/----",
    "th13_ascii_spell_game": "GAME MODE        %4d/%4d",
    "th14_ascii_bonus": "BONUS %.1f",
    "th14_ascii_no_bonus": "NO BONUS",
    "th10_ascii_stage_1": "Stage 1",
    "th10_ascii_stage_2": "Stage 2",
    "th10_ascii_stage_3": "Stage 3",
    "th10_ascii_stage_4": "Stage 4",
    "th10_ascii_stage_5": "Stage 5",
    "th10_ascii_stage_6": "Stage 6",
    "th10_ascii_stage_clear": "Clear",
    "th10_ascii_score_empty": "%2d  %s  %9ld%d  ----/--/-- --:--  Stage -  ---%",
    "th10_ascii_ranking": "           Score Ranking!!",
    "th13_ascii_credit": "Credit %d",
    "th16_ascii_score_empty": "%2d  %s  %9ld%d  ----/--/-- --:-- Season  Stage -  ---%%",
    "th16_ascii_score_spring": "Spring",
    "th16_ascii_score_summer": "Summer",
    "th16_ascii_score_autumn": "Autumn",
    "th16_ascii_score_winter": "Winter",
    "th16_ascii_score_sp": "Sp",
    "th16_ascii_score_sm": "Sm",
    "th16_ascii_score_at": "At",
    "th16_ascii_score_wt": "Wt",
    "th165_ascii_replay_empty": "No.%.2d ------------ --/--/-- ---------",
    "th165_ascii_replay_sun": "   Sun",
    "th165_ascii_replay_mon": "   Mon",
    "th165_ascii_replay_tue": "   Tue",
    "th165_ascii_replay_wed": "   Wed",
    "th165_ascii_replay_thu": "   Thu",
    "th165_ascii_replay_fri": "   Fri",
    "th165_ascii_replay_sat": "   Sat",
    "th165_ascii_replay_sun2": "2nd Sun",
    "th165_ascii_replay_mon2": "2nd Mon",
    "th165_ascii_replay_tue2": "2nd Tue",
    "th165_ascii_replay_wed2": "2nd Wed",
    "th165_ascii_replay_thu2": "2nd Thu",
    "th165_ascii_replay_fri2": "2nd Fri",
    "th165_ascii_replay_sat2": "2nd Sat",
    "th165_ascii_replay_sun3": "3rd Sun",
    "th165_ascii_replay_mon3": "3rd Mon",
    "th165_ascii_replay_tue3": "3rd Tue",
    "th165_ascii_replay_wed3": "3rd Wed",
    "th165_ascii_replay_thu3": "3rd Thu",
    "th165_ascii_replay_fri3": "3rd Fri",
    "th165_ascii_replay_sat3": "3rd Sat",
    "th165_ascii_replay_diary": "  Diary",
    "th06 Stats ReimuA": "하쿠레이 레이무 (영부)",
    "th06 Stats ReimuB": "하쿠레이 레이무 (몽부)",
    "th06 Stats MarisaA": "키리사메 마리사 (마부)",
    "th06 Stats MarisaB": "키리사메 마리사 (연부)",
    "th06_ascii_centered_stage": "STAGE %d",
    "th06_ascii_centered_stage_final": "FINAL STAGE",
    "th06_ascii_centered_stage_extra": "EXTRA STAGE",
    "th06_ascii_centered_stage_demo": "DEMO PLAY",
    "th06_ascii_centered_spell_bonus": "Spell Card Bonus!",
    "th06_ascii_fullpower": "Full Power Mode!!",
    "th06_ascii_bonus_format": "BONUS %8d",
    "th06_ascii_clear_header_all": "All Clear!",
    "th06_ascii_clear_header": "Stage Clear",
    "th06_ascii_clear_bonus_stage": "Stage * 1000 = %5d",
    "th06_ascii_clear_bonus_power": "Power *  100 = %5d",
    "th06_ascii_clear_bonus_graze": "Graze *  10 = %5d",
    "th06_ascii_clear_bonus_point": "   * Point Item %3d",
    "th06_ascii_clear_bonus_player": "Player    = %8d",
    "th06_ascii_clear_bonus_bomb": "Bomb      = %8d",
    "th06_ascii_clear_bonus_easy": "Easy Rank      * 0.5",
    "th06_ascii_clear_bonus_normal": "Normal Rank    * 1.0",
    "th06_ascii_clear_bonus_hard": "Hard Rank      * 1.2",
    "th06_ascii_clear_bonus_lunatic": "Lunatic Rank  * 1.5",
    "th06_ascii_clear_bonus_extra": "Extra Rank    * 2.0",
    "th06_ascii_clear_bonus_penalty_0.5": "Player Penalty * 0.5",
    "th06_ascii_clear_bonus_penalty_0.2": "Player Penalty * 0.2",
    "th06_ascii_clear_bonus_total": "Total    = %8d",
    "th06_ascii_replay_header": "No.  Name      Date    Player  Rank",
    "th06_ascii_replay": "%s %8s  %8s %-7s  %-7s",
    "th06_ascii_replay_save_empty": "No.%.2d -------- --/--/-- -------          0",
    "th06_ascii_replay_save_header": "No.  Name    Date    Player  Score",
    "th06_ascii_replay_save": "No.%.2d %8s %8s %7s %10d",
    "th06_ascii_2_digit_number_format": "No.%2d",
    "th06_ascii_replay_user": "User",
    "th06_ascii_reimu_a": "ReimuA",
    "th06_ascii_reimu_b": "ReimuB",
    "th06_ascii_marisa_a": "MarisaA",
    "th06_ascii_marisa_b": "MarisaB",
    "th06_ascii_easy": "Easy",
    "th06_ascii_normal": "Normal",
    "th06_ascii_hard": "Hard",
    "th06_ascii_lunatic": "Lunatic",
    "th06_ascii_replay_stage_header": "Stage  LastScore",
    "th06_ascii_extra": "Extra",
    "th06_ascii_replay_stage_empty": "%-6s  ---------",
    "th06_ascii_replay_stage": "%-6s %10d",
    "th06_ascii_replay_stage_1": "Stage1",
    "th06_ascii_replay_stage_2": "Stage2",
    "th06_ascii_replay_stage_3": "Stage3",
    "th06_ascii_replay_stage_4": "Stage4",
    "th06_ascii_replay_stage_5": "Stage5",
    "th06_ascii_replay_stage_6": "Stage6",
    "th06_ascii_replay_stage_extra": "Extra",
    "th06_ascii_result_clear": "(C)",
    "th17": "동방귀형수 ~ Wily Beast and Weakest Creature.",
    "th16 Dialog Fullscreen": "전체 화면",
    "th16 JP": "동방천공장",
    "th17 JP": "동방귀형수",
    "th17 config": "동방귀형수 환경설정",
    "th16 half rate": "1/2회",
    "th16 third rate": "1/3회",
    "th16 refresh rate": "출력 간격",
    "th16 full rate": "매번 (권장)",
    "th16 no save": "저장하지 않고 종료",
    "th16 input latency": "입력 지연 시간",
    "th16 slowshot": "샷 버튼을 누르고 있으면 저속이동을 합니다",
    "th16 normal input": "보통 (CPU 점유율 낮음)",
    "th16 automatic input": "자동 (최적의 반응 속도를 자동으로 뽑아냄) *권장",
    "th16 stable input": "안정 (보통 선택 시 제대로 움직이지 않는 경우)",
    "th16 fast input": "고속 (자동 선택 시 정상 작동하지 않는 경우)",
    "th16 input description": "입력 지연 시간 옵션으로 입력 반응을 조금씩 조정할 수 있습니다.\n'안정' '보통'은 이전 작품까지의 반응 속도입니다.\n'자동'은 컴퓨터의 성능이 충분하면 빠른 반응을 기대할 수 있습니다.\n'고속'은 '자동'과 같은 지연 속도이지만, 일부 화면이 깨지는 경우가 있습니다.\n*다시 그리기 간격이 '매회'일 때는 무시됩니다*",
    "th16 sensitivity description": "방향키 입력이 둔한 경우에는 줄이고, 너무 민감하면 늘려 주세요\n(기본값: 600)",
    "th16 Dialog Always ask": "실행할 때마다 묻기",
    "th16 joypad sensitivity": "게임 패드 감도",
    "th16 default": "설정 초기화",
    "alcostg": "황혼주점～Uwabami Breakers～",
    "th135": "동방심기루 ~ Hopeless Masquerade.",
    "th145": "동방심비록 ~ Urban Legend in Limbo.",
    "th155": "동방빙의화 ~ Antinomy of Common Flowers.",
    "nsml": "마리사와 6개의 버섯 - New Super Marisa Land",
    "megamari": "MegaMari - 마리사의 야망",
    "marilega": "MarisaLand Legacy",
    "th17 Trophy Get": "업적을 얻었다",
    "th175": "동방강욕이문 ~ 수몰된 침수지옥",
    "th18": "동방홍룡동 ~ Unconnected Marketeers.",
    "th16 save": "저장하고 종료"
}